### ISSUE TITLE
3.1.2 hadoop安装 北理工镜像站wget安装失败

### ISSUE THREAD

**Issue by trevery** [Wanghui-Huang/CQU_bigdata#1]
![image](https://user-images.githubusercontent.com/11856849/93440973-37d24780-f902-11ea-8f30-34bfcc3baf26.png)

这一步貌似因为证书问题以及版本出错。

> ~  sudo wget -O hadoop-2.8.5.tar.gz https://mirrors.cnnic.cn/apache/hadoop/common/hadoop- 2.8.5/hadoop-2.8.5.tar.gz
--2020-09-17 16:24:56--  https://mirrors.cnnic.cn/apache/hadoop/common/hadoop-
Resolving mirrors.cnnic.cn (mirrors.cnnic.cn)... 101.6.8.193, 2402:f000:1:408:8100::1
Connecting to mirrors.cnnic.cn (mirrors.cnnic.cn)|101.6.8.193|:443... connected.
ERROR: cannot verify mirrors.cnnic.cn's certificate, issued by '/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA':
  Issued certificate has expired.
To connect to mirrors.cnnic.cn insecurely, use `--no-check-certificate'.
--2020-09-17 16:24:56--  http://2.8.5/hadoop-2.8.5.tar.gz
Resolving 2.8.5 (2.8.5)... 2.8.0.5
Connecting to 2.8.5 (2.8.5)|2.8.0.5|:80...

我是在本地下载的hadoop tar包，scp上传到服务器然后解压的。建议可以更换源，或者解决证书问题。另外北理工的版本号似乎也发生了变化。

**Comment by Wanghui-Huang** [comment]
经测试，并非在每位同学机器都会出现该问题，如果出现该问题可先按照该方法进行解决。
后续会更新文档，更新该问题解决方法。

**Comment by CCXMing** [comment]
> 经测试，并非在每位同学机器都会出现该问题，如果出现该问题可先按照该方法进行解决。
> 后续会更新文档，更新该问题解决方法。

有这个问题的在后面加上免证书验证就可以了 --no-check-certificate

**Comment by Wanghui-Huang** [comment]
已更新到最新文档，所以该issue被关闭。
