### ISSUE TITLE
集群遭受挖矿病毒攻击的相关问题

### ISSUE THREAD

**Issue by KarlThelor** [Wanghui-Huang/CQU_bigdata#10]
![image](https://user-images.githubusercontent.com/60059677/96732961-81272280-13eb-11eb-985e-b2c6d07e9648.png)
集群的服务器遭受了挖矿病毒的攻击，有种方法是写定时任务来删除病毒的相关文件，可总是治标不治本。因为挖矿病毒不止一种，有什么比较好的解决方法吗？

**Comment by Archaon6734** [comment]
不连集群还好，连上集群的服务器有的也遭受了DDOS攻击的问题![image](https://user-images.githubusercontent.com/58738002/96735044-b9c7fb80-13ed-11eb-98f8-f790b6bc7ce2.png)

**Comment by Archaon6734** [comment]
我们组的centos 服务器通过查询 var/log/secure日志 发现有人通过master半夜免密登录slave搞破坏
![image](https://user-images.githubusercontent.com/58738002/96736925-addd3900-13ef-11eb-94c8-5aea13435248.png),也许将环境配置好后将服务器的端口不暴露给公网能解决这个问题。

**Comment by trevery** [comment]
感谢分享该问题，建议查看一些服务器安全保护的文章，试着做一些简单的保护，比如禁止root用户登陆，防止暴力破解密码。限制密码输入次数、更改ssh端口号等。可以显著避免服务器被黑。
针对DDOS攻击，建议不使用的时候关闭相关进程。
