### ISSUE TITLE
spark worker之间的通信问题

### ISSUE THREAD

**Issue by Archaon6734** [Wanghui-Huang/CQU_bigdata#11]
配置好spark集群后，提交完计算任务时，集群的slave之间的私网ip无法互相通信，但slave能和master正常通信
![image](https://user-images.githubusercontent.com/58738002/97100386-dbff9900-16cd-11eb-9c39-9cd13b117006.png)
我们有两台阿里云，两台腾讯云服务器，是因为他们公网的网段不同使得他们无法用私网ip进行局域网通信吗？

**Comment by Wanghui-Huang** [comment]
如果你是指slave之间无法通信，
1. slave节点的相关端口放开了吗？你可以尝试登陆你的**每台**slave云服务器控制台，尝试：
- 新建安全组，设置出站/入站 放通所有端口
- 将slave对应的云服务器加入新建的安全组
- 重启集群，查看问题是否解决

2. 为什么你的，如slave1 和其他如slave2节点通信会是以内网ip呢？在相关配置文件的时候不该出现这种情况啊。

**Comment by Archaon6734** [comment]
好的，我们重启试试看

**Comment by Wanghui-Huang** [comment]
后续还出现问题，请私聊我qq就行。我可以帮你们远程看看。

**Comment by Wanghui-Huang** [comment]
另外，出现该问题原因，还可能是37687这个端口已经被占用了，可以尝试下面杀死占用端口的进程：
![image](https://user-images.githubusercontent.com/23701880/97101357-a9f33480-16d7-11eb-995b-5829d5ce0682.png)
----------------------------------------------------------------
特别的，我上面提出的解决办法都是针对端口问题。如果以上都无法解决，便是ip之间不互通问题。等你后续反馈，我再来修改下你的配置文件为外网ip，看他们是否能成功运行任务。

**Comment by Archaon6734** [comment]
好了，谢谢助教
