### ISSUE TITLE
lab1 lab2 遇到的一些问题与解决方法

### ISSUE THREAD

**Issue by OKAZ1999** [Wanghui-Huang/CQU_bigdata#16]
### **Lab 1 :**

1. 北理工的hadoop-2.8.5链接失效
2. hadoop & spark配置失败与安全组

[ 1 ] 北理工的Hadoop-2.8.5链接失效:

替换为2.92版本 ： https://mirrors.cnnic.cn/apache/hadoop/common/hadoop-2.9.2/hadoop-2.9.2.tar.gz

[ 2 ] hadoop & spark配置失败问题与服务器安全组的配置

安全组中入口添加端口 8080，9001，9000，50070

### **Lab 2 :**
1. Chrome 报错
2. 中文乱码与字体资源缺失

[ 1 ] Chrome 报错
原因：sudo yum install https://dl.google.com/linux/direct/google-chromestable_current_x86_64.rpm 安装的chrome是87版本的
但 sudo yum install chromedriver.x86_64 会下载85版本的

`google-chrome --version`     查看版本，如果没有，请先下载运行第一条yum install 
[https://npm.taobao.org/mirrors/chromedriver/](https://npm.taobao.org/mirrors/chromedriver/) 下载相应版本驱动   
`unzip chromedriver_linux64.zip`  自行解压
`mv chromedriver /usr/local/bin/`  放到环境中
`chmod +x /usr/local/bin/chromedriver` 更改权限

[ 2 ] 中文乱码与字体资源缺失

原因：给的文件中没有考虑到服务器差异，也缺失相关配置介绍

参考csdn博客：[https://blog.csdn.net/wlwlwlwl015/article/details/51482065](https://blog.csdn.net/wlwlwlwl015/article/details/51482065)

### **Lab 3**
1. 上传hdfs文件失败

[ 1 ] 上传hdfs文件失败

安全组配置原因：参考lab1设置

**Comment by Wanghui-Huang** [comment]
感谢反馈，问题已修复&贡献已记录。
