### ISSUE TITLE
2.2.2节-获取桌面环境失败

### ISSUE THREAD

**Issue by trevery** [Wanghui-Huang/CQU_bigdata#2]
## 问题描述：我在自己电脑的终端（terminal or putty）里面使用ssh运行如下界面，并没有进入图形界面。

```
yum groupinstall "GNOME Desktop" "Graphical Administration Tools"
startx
```
## 回答：
应该在阿里云或者腾讯云提供的网页版本的控制台（终端）中输入startx才可以打开图形界面。以阿里云为例：

![image](https://user-images.githubusercontent.com/11856849/93450131-2d1ab100-f908-11ea-9113-b9ac45d3b745.png)

在实例详情里面点击远程连接下的VNC。跳转至页面

![image](https://user-images.githubusercontent.com/11856849/93449763-b7164a00-f907-11ea-8305-f871156671f0.png)

输入密码（可以修改）。
初次运行应该是CLI界面，可以运行如上上述命令安装桌面环境，运行startx命令打开桌面环境，就可以通过VNC进入桌面环境。

## 可选方法：（可以避免每次登陆vnc输入密码）
在服务器上安装vnc软件（比如realvnc server），在相应的vnc客户端（比如 vnc viewer）中访问图形界面。如下图

![image](https://user-images.githubusercontent.com/11856849/93450353-74a13d00-f908-11ea-8f5a-7d62fdfae9f7.png)

**Comment by Wanghui-Huang** [comment]
感谢提出问题，已更新最新文档，对应章节引入issue链接。
