### ISSUE TITLE
lab1、2小细节问题

### ISSUE THREAD

**Issue by wdd-spec** [Wanghui-Huang/CQU_bigdata#20]
记录1：
**3.2.2 Hadoop集群配置**第二步修改文件slaves**
hadoop3.x.x后的版本【slaves更名为workers】

3.2.3 Spark集群配置同理

记录2：
**ERROR：node02：Cannot set priority of xxxxxx process on PID xxxx**
节点配置：master节点传到slave节点的文件，有内容要修改最好master节点修改重发，在各自节点上更改可能导致某种不可见的文件格式不一致（确实改得一模一样），进而导致该问题。
怎么也没想到是这个问题，毕竟指导里也可以在slave节点上各自配置，而非通过传文件，但确实重发覆盖原文件后病就好了

记录3：
**出现信息.....failed with error code 1 in /tmp/pip-build-.......**
更新pip3

**Comment by Wanghui-Huang** [comment]
感谢，已经修复相关问题。
