### ISSUE TITLE
实验二执行 bin/spark-submit /home/hadoop/Experiment/Ex2_WordCount/WordCount.py可能遇到的一些问题

### ISSUE THREAD

**Issue by a-fly-fly-bird** [Wanghui-Huang/CQU_bigdata#21]
# 首先展示最终要达到的结果
## 关闭可视化
![image](https://user-images.githubusercontent.com/70647529/140508483-2e5c9565-8787-46cb-96ed-73cfe45705ad.png)
## 开启可视化
![image](https://user-images.githubusercontent.com/70647529/140509633-d21b1914-5dab-4066-9f28-0dbe79e7a799.png)
![词云可视化](https://user-images.githubusercontent.com/70647529/140509777-2fb79780-398e-4b1b-92cf-191f8cbd987a.png)
![饼图可视化](https://user-images.githubusercontent.com/70647529/140509780-1fdc8c81-7dee-410d-a9b1-a525225ee45f.png)

# 遇到的问题
### 报错信息
![image](https://user-images.githubusercontent.com/70647529/140507814-637817ed-2b49-48a3-bc12-4ba53c777a6c.png)
### 解决方案
更新pip3
`sudo pip3 install --upgrade pip `
然后重新安装对应的包

### 报错信息
Selenium: WebDriverException:Chrome failed to start: crashed as google-chrome is no longer running so ChromeDriver is assuming that Chrome has crashed
### 解决方案
1. 首先确保自己不是在root用户下运行命令。
在root用户下启动chrome会报类似下面的错误：
“ERROR:zygote_host_impl_linux.cc (90)] Running as root without --no-sandbox is not supported. 
找了半天解决方案，我发现最高效的解决方法还得是不在root用户下运行chrome.

2. 在visualize.py 中添加如下代码:
`from selenium import webdriver`
`from selenium.webdriver.chrome.options import Options`

`chrome_options = Options()`
`chrome_options.add_argument('--headless')`
`chrome_options.add_argument('--no-sandbox')`
`chrome_options.add_argument('--disable-dev-shm-usage')`

### 报错信息
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81
### 问题分析
报次错误说明安装ChromeDriver 和 Chrome 的版本不兼容。安装的ChromeDriver 版本一定要跟 chrome 版本匹配的上才行。
如果不确定自己的版本，这里给出查看版本号的命令：
![image](https://user-images.githubusercontent.com/70647529/140511329-2b953728-a5de-40c6-b13c-37abdfd2af29.png)
### 解决方案
重新安装与chrome版本匹配的 ChromeDriver。
首先去国内的ChromeDriver镜像网站网址：https://npm.taobao.org/mirrors/chromedriver查找版本。
例如我的Chrome是95的，那么我的驱动也应该选择95对应的。
命令行执行
`cd /usr/local/bin/`
`ls`
![image](https://user-images.githubusercontent.com/70647529/140513544-5dbdd077-1c81-4e95-b43b-2dfb71cfa2cc.png)
删除当前的chromedriver
rm -rf chromedriver
然后使用wget命令下载新的ChromeDriver
`wget https://npm.taobao.org/mirrors/chromedriver/95.0.4638.54/chromedriver_linux64.zip`
`unzip chromedriver_linux64.zip`
`chmod 777 chromedriver`
再查看版本号。
另外给出google-chrome的卸载和安装的命令
卸载：运行 yum remove google-chrome 然后以 Tab 补全所有整个命令，再加上 - y 参数
安装：yum install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

### 报错信息
类似 open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory或者其他的
### 解决方案
这边建议首先确定自己的图形化界面是否安装成功。
这里给出我的**阿里云ECS CentOS8** 安装图形界面的方法：
1. 安装图形桌面的软件包。`yum groupinstall "Server with GUI" -y`
2. 设置图形模式为默认模式启动 `systemctl set-default graphical`
3. 重启服务器，重启后即可通过阿里云网页控制台上的 VNC 连接看到图形界面。要出现如下界面才算成功。黑乎乎的没有成功。
![image](https://user-images.githubusercontent.com/70647529/140515021-4a91b497-3be6-42c4-9d5f-34ca9a4bed55.png)
其他的云平台和操作系统的操作方法有一些差别，请自己在搜索引擎上搜索。

## Q5. Python报告权限错误：[errno 13] 权限被拒绝
这里我举两种情况：
#### 报错信息
PermissionError: [Errno 1] Operation not permitted: '/tmp/tmpg255ml7f' -> '/tmp/jieba.cache'
#### 问题分析
这是因为 jieba 默认情况下在 /tmp 下存储缓存文件，然而不是 root 用户，权限不够。解决办法是修改默认缓存文件的目录，把缓存文件放在用户的目录下面。 jieba 文档提到了 tmp_dir 和 cache_file 可以改，所以我们查看了下源码
#### 解决方案
切换到报错的目录，查看init文件
比如我的
`vim /usr/local/lib/python3.6/site-packages/jieba/__init__.py`
将self.tmp_dir 赋值为用户目录下的任意目录。如下图
![image](https://user-images.githubusercontent.com/70647529/140518379-b7c93055-df45-4409-8e96-4f1ebfcbd7f5.png)
#### 报错信息
![image](https://user-images.githubusercontent.com/70647529/140516117-8734c954-7578-4428-bccd-6d9c4d27e23d.png)
#### 解决方案
首先切换到spark目录
`cd /usr/local/spark`
可以看到改目录下有render.html文件，hadoop用户没有操作的权限
![image](https://user-images.githubusercontent.com/70647529/140519216-60dd4e57-057f-48b4-ad3a-226bef3de64b.png)
最简单的方法时给Other用户读写的权力即可
`sudo chmod 777 render.html`

### 报错信息
报错大概如下（我当时忘记截图了，图片来自网络，侵删）
![image](https://user-images.githubusercontent.com/70647529/140520039-07bcc908-5d52-47ee-a2a4-03b62eb210a9.png)
### 解决方案
`pip3 uninstall snapshot-selenium`
`pip3 install snapshot-selenium`
问题解决

## Q7. 字体的问题
visualize.py 给出的 font_path='/usr/share/fonts/wqy-microhei/wqy-microhei.ttc'。 如果你发现/usr/share/fonts下没有这款中文字体，那么运行时会报错。
我去查了一下，这款字体叫文泉驿微米黑，是开源免费的。
安装该字体的命令：
`sudo yum install wqy-microhei-fonts`

### 报错信息
selenium. common. exception. webdriver exception: message: chrome not reachable
### 解决方案
查看issue 5.
https://github.com/Wanghui-Huang/CQU_bigdata/issues/5

---
以上就是我执行该命令过程中遇到的所有问题。可能并不具有通用性。如有纰漏，欢迎交流和批评指正。

**Comment by Wanghui-Huang** [comment]
很惭愧，代码是在两年前的写的，错误颇多。今年由于也并非是这门课的正式助教，去实习等原因没有去更新代码。
所有错误已经修改记录到文献中，特别的：
- 已邀请你作为本次开源课程的贡献者；
- 已特别和今年的助教师弟注明了你的贡献，本次实验提名为满分。
今年年底正式参加工作前，我会尽量将所有实验重写一遍，如果你有更好的想法可和我联系。
