### ISSUE TITLE
实验一 Spark3.1.2版本Web UI无法正常正常显示worker的一种解决方案

### ISSUE THREAD

**Issue by leexinhao** [Wanghui-Huang/CQU_bigdata#22]
使用Spark3.1.2安装文档操作，前面一切正常（除了slaver要换成worker），`Web UI` 却无法正常正常显示worker。

![image](https://user-images.githubusercontent.com/48858574/140900593-264720f7-f3c3-4f2b-84dd-64086ef21458.png)

查看slave日志文件发现连接master失败了：

![image](https://user-images.githubusercontent.com/48858574/140900312-6b5a57cf-7dd0-48f3-9f21-9053ba1860af.png)

使用nmap工具在Slave主机用如下命令测试：

```bash
nmap -p 7077 master_ip
```

确认7077端口是可以连接的。

注意到日志中slaver是以master的内网IP192.168.1.219进行连接的，考虑将slave文件中：

![image](https://user-images.githubusercontent.com/48858574/140900374-ad979847-ff77-46e4-9e29-6beef90bb1a3.png)

填写的`SPARK_MASTER_HOST`改为`master`，以便master服务器和slave服务器可以根据它们各自的hosts文件对master_ip进行映射后问题解决：
![image](https://user-images.githubusercontent.com/48858574/140900429-a34a8556-cfcd-474f-898b-9604da4b9b01.png)

**Comment by Wanghui-Huang** [comment]
感谢参与建设，已修改文档错误，已记录贡献。
