### ISSUE TITLE
实验三：指导书外报错汇总

### ISSUE THREAD

**Issue by Wangzt670** [Wanghui-Huang/CQU_bigdata#24]
# 实验三：指导书外报错汇总

by 王正霆20194249 王开发20194235 崔晋20191682

### 1*无法连接问题

注意这一步需要先启动集群否则会报错

### 2*指导书前后不一致

注意指导书上这里前后不一致，需要统一（代码里面的路径是/ex/ex3dataset/iris.data)

传输前根据报错提示将 9866 端口同时添加到 master 以及 slave 的安全组

传输结果如图

![image-20211109145619369](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211109145619369.png)

### 1*编码问题

同实验二，若出现编码报错，除了规定部分的代码填写，还需要把编码方式由 utf8 改为 UTF-8

![image-20211109152233335](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211109152233335.png)

### 2*computeCost() 无法识别

注意 pyspark2 中可以使用 computeCost() 方法，但是 pyspark3 中删除了此方法，只能通过以下解决方案进行代替（此方法评估模型方法不同，故最后的画图结果与正确结果不同）

![image-20211110192454450](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211110192454450.png)

### 3*集群运行显示内存不足

按步骤启动集群，提交代码，遇到报错如下

```
Initial job has not accepted any resources; check your cluster UI to ensure that workers are regist
```

显示为内存不足，但是经过检查剩余内存足够并且此程序占用内存较小，可以按如下解决方案依次尝试

![image-20211110193022697](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211110193022697.png)

若最终仍旧未能解决，只能在spark单机环境下运行测试

这是集群内存不足报错强行kill掉程序后显示的结果

![image-20211109153101259](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211109153101259.png)

**Comment by Wanghui-Huang** [comment]
感谢反馈，问题已记录 & 贡献已反馈。
