### ISSUE TITLE
Lab1-3的一些遇坑与填坑记录

### ISSUE THREAD

**Issue by Yizhang-Zhu** [Wanghui-Huang/CQU_bigdata#25]
# Lab1-3的一些遇坑与填坑记录

by 20194113朱绎彰 20194114何钰煌  20194109张一帆

实验中搞崩环境重装系统已经至少六七次了，虽才疏学浅，但还是勉强汇成一部遇坑和填坑的经历史，记录我们遇到的部分github上暂时没有提及的困难和**可能可行**解决的办法。希望来者可以在前人的血泪史中汲取经验，顺顺利利地完成实验！
如有谬误还望各位大佬批评指正。

### 1. Lab1中SSH登录：WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!的问题

master免密登录slave结点，但是ssh回master可能出现问题，大致如下：

![image](https://user-images.githubusercontent.com/58728570/142751331-c547a99b-4817-48e0-b988-85694544e91e.png)

解决：vim进入`~/.ssh/known_hosts`，删除文件里与master的ip相关的那一项，重试一般就没问题了.

### 2. Lab2中chromedriver和google-chrome版本不匹配，尝试github上issue #21 Q3中方法多次还是不行

如果尝试下载并多次，还是提示版本号不兼容，一定要查看原来的chrome-driver是否删干净了，注意以下两个地方：

1. 尝试通过以下指令删除chrome-driver

   ```shell
   sudo rm -f /usr/bin/chromedriver
   sudo rm -f /usr/local/bin/chromedriver
   sudo rm -f /usr/local/share/chromedriver
   ```

   也可以再检查下是否有其他残余：

   ```shell
   sudo find / -name "chromedriver"
   ```

2. 【大坑注意！】如果尝试了多次不成功，一定记得`ls`一下检查下载zip文件的目录！

   因为你尝试了多次可能下载了多个zip文件，centOS会自动在文件名后面编号。如下图，我们这里就下了一堆zip:

![image](https://user-images.githubusercontent.com/58728570/142751339-f9a921f3-3b01-4621-9c95-656206da26f7.png)

   而如果你不知道这种情况的话，你每次解压的都是最老的文件，所以每次尝试其实都是一样的，没差别，所以可能每次都失败。

   因此，要用`remove XXX`把上面那些zip全部删了先，然后再`wget`下载最新的，并解压`unzip chromedriver_linux64.zip`，设置权限`chmod 777 chromedriver`，这样一波操作下来估计就可以了

### 3. 上一个问题解决后`rpm -qa |grep -i chrome`查询chrome信息发现还是版本不一致的问题

其实这个问题有点玄学，我们执行了上面的操作之后，输入`rpm -qa |grep -i chrome` 查询chrome和chromedriver的信息后发现还是不匹配：chrome我们是96，而chromedriver还是原来的90，我们以为又失败了，但是通过`chromedriver`查询，却发现chromedriver的version已经是96了...实际运行下面的操作也没有问题，所以这个事情或许可以不管。

![image](https://user-images.githubusercontent.com/58728570/142751343-4b4a5a33-d0ad-4da9-a088-515cf2180f97.png)

### 3. Lab2/Lab3可能出现文件权限不够的问题

解决：对上传的整个Experiment文件夹执行以下命令修改权限：

```shell
cd ~
chmod -R 777 Experiment
```

### 4. Lab3实验指导书上传hdfs部分文件夹路径出错

![image](https://user-images.githubusercontent.com/58728570/142751357-68071dc4-0a04-40cf-b505-263aa4210467.png)

### 5. Lab3内存问题

1. `bin/spark-submit --master spark://master:7077 --py-files /home/hadoop/Experiment/Ex3_KmeansI/kmeans.py --executor-memory 1G /home/hadoop/Experiment/Ex3_KmeansI/iris.py`中1G内存可以改小为500M（这个最新的issu）已经提到了，但是要注意不能改到太小，不然会提示至少要XXX内存，换算了一下这个下限大概是450M。

2. 内存不足重启是有效的，不想这么麻烦也可以先在`cd /usr/local/spark`和`cd /usr/local/haddop`下停止集群：

   ```shell
   # /usr/local/spark下
   cd /usr/local/spark
   sbin/stop-master.sh 
   sbin/stop-slaves.sh
   # /usr/local/hadoop下
   cd /usr/local/hadoop
   sbin/stop-all.sh
   ```

   一般来讲，停止后内存占用会很快减轻，然后再启动集群跑一次可能就可以了。

   查看资源占用可以使用图形界面的monitor，也可以在控制台直接查看资源占用情况（腾讯云）：

 ![image](https://user-images.githubusercontent.com/58728570/142751361-33c3e4d1-7e5d-40ba-8b00-74fe7595e904.png)

**Comment by Wanghui-Huang** [comment]
感谢分享，非常好的反馈。已记录组成员贡献。
