### ISSUE TITLE
实验一~实验三的坎坷之路记录 && 实验三的奇迹再现

### ISSUE THREAD

**Issue by KOBEliever** [Wanghui-Huang/CQU_bigdata#28]
## 写在前面
大数据实验可谓是遇到了九九八十一难，无数次想过放弃，但是在助教、同学的帮助和我们的努力下，都或多或少的解决了，就像一句话所说  **“人生就像闯关游戏，遇到困难，说明你的路走对了”** 
为了让后来者尽量少的走我们走过的弯路，我们写下这篇issue，希望能对大家有所帮助
这是我们第一次写issue，哪里写得不具体还请见谅🙇
### 最有用的方法！💰💰💰
我们在一开始使用的云服务器是腾讯云的学生优惠，配置较低，在实验一、二、三均遇到了配置过低导致的问题
后面参考 #27 用HuaWei❤️❤️❤️发的优惠券，配置拉满，能够规避绝大多数问题🎆
##### 悲剧再现
万万没想到，我们开始就中招了😫，一切的来源归咎于那个月黑风高的晚上：
我使用master节点，复制Spark文件到各个slave节点
```
cd /usr/local/
tar -zcf ~/spark.master.tar.gz ./spark
cd ~
scp ./spark.master.tar.gz slave01:/home/hadoop
```
传输速度非常之慢🙄要传一个小时，于是我就把电脑开着让它传输，上床去睡觉了，
结果第二天早上，我们就收到了惊喜‼️
![QQ图片20211128144528](https://user-images.githubusercontent.com/77789779/143732533-c37d05c3-1f53-4ea9-a40f-228191d6dacd.jpg)
##### 解决方法
还以为是恶作剧，咨询了助教并查询了 #10 之后，选择了**重装系统**📴,然后**再也没尝试过晚上传输数据**，可能是腾讯云的问题
##### 悲剧再现
换了华为云之后实验1非常的顺利！🦾，花钱之后速度非常的快！不管是下载还是master与worker之间的文件传输！💵 **有钱才是王道！**
直到我打开webUI：状态是alive但是worker下没有一个节点
![image](https://user-images.githubusercontent.com/77789779/143732786-7afec314-1f4b-4640-86ca-80abc07218a8.png)
查看日志，错误大概是worker没有连接到master的7077端口 `WARN Worker: Failed to connect to master 10.xx.xx.xx:7077`
##### 解决方案
通过其他兄弟姐妹的issue和google、**StackOverflow**、博客园、CSDN的帮助，有两种可能的原因：网络连接问题和Spark连接问题，对此我尝试了大概5️⃣种方法

**1. 华为云新建安全组，开放所有端口并将实例加入规则**🌟
![image](https://user-images.githubusercontent.com/77789779/143733175-b96b95d8-19e4-4a26-8614-736b5e583a50.png)
![image](https://user-images.githubusercontent.com/77789779/143733186-5b7f0ac1-6dc7-4d4d-8cc6-7dc4efaddd72.png)
![image](https://user-images.githubusercontent.com/77789779/143733203-a0c5cb06-6ef9-46f2-a05e-e0ee737f0863.png)
重启集群之后查看webUI成功！
2. 关闭防火墙
3. 修改spark-env.sh
#22 或改参数名PORT为HOST
4. 添加master启动参数
 ```
./sbin/start-master.sh -h master_ip
./sbin/start-slave.sh spark://master_ip:7077
```
#3 
5. 再次重装系统，但是最后还是通过安全组解决

#### 解决：
更新pip3
`sudo pip3 install --upgrade pip`
然后重新安装对应的包
#### 解决： #21 
@a-fly-fly-bird 我的室友很强🐂我很骄傲🐶
#### 问题一 创建hdfs文件夹失败
没错，我们在做实验3时马上就遇到了问题
![)6 CIAP1%DS@J4WAM 05E H](https://user-images.githubusercontent.com/77789779/143731977-4d0f0679-7c8c-435a-84e5-8c92f8c24e45.png)
我们尝试了很多办法，比如关闭防火墙、安全组一键放通、重启集群、重启服务器等等
但是都有问题
于是乎，我们又一次重装了系统😫，已经数不清是第几次了，重装系统之后按步骤做终于做成了
但是，因为腾讯云的学生机配置太低，在运行最后的代码时，还是出现了资源不足的问题
![}XPQ_O`J6DP9069XB3Q7V99](https://user-images.githubusercontent.com/77789779/143733875-7a7722bc-f184-42e7-bd96-d099152ce2fc.png)
相对于改配置文件、重启集群、将命令中的1G改为512M
我们用血与泪的教训建议，**花钱**，换好配置，华为云发了券，所以建议在**实验1就配置高配置华为云**
#### 问题二 上传数据集失败
在上传数据集时，我们遇到了以下报错：
![989A31400B39AEE28374ADCEE7CA6A14](https://user-images.githubusercontent.com/77789779/143733907-d59450e9-4178-4e35-ba3d-a2cfa755607f.png)
![C9C7C19D725FE1DF4F110549EC8FED42](https://user-images.githubusercontent.com/77789779/143733936-f6b69dbc-6a63-4ce5-8828-abcd703ce90b.png)

貌似是端口9866被占用了，而且datanode都连接失败了
对此我在StackOverflow上查询了很多方法，比如
##### 1.格式化namenode
![image](https://user-images.githubusercontent.com/77789779/143734012-64b883d1-107e-4793-bb55-cf33ece1cd67.png)
##### 2.删除datanode再重启
![image](https://user-images.githubusercontent.com/77789779/143734021-3c46af3c-d9fc-47df-a8a3-9f377d21460b.png)
##### 3.向hdfs-site.xml中添加将dfs.client.use.datanode.hostname置为true
![image](https://user-images.githubusercontent.com/77789779/143734114-0304878a-a482-4f15-a263-3ab909a593fe.png)

但是都没有奏效，在两个woker上也上传失败，这时候已经五点了，就上去睡觉了
**结果第二天worker02突然可以上传数据集并运行成功**
![image](https://user-images.githubusercontent.com/77789779/143734271-5d3021aa-da9d-4864-bf0e-7966e3f812cb.png)
但是master和worker01还是不行
还是同样的`org.apache.hadoop.net.ConnectTimeoutException: 60000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=worker02/139.9.231.240:9866]`

很奇怪😂睡一觉莫名其妙就可以了，但是只有worker02可以，我们很疑惑😕
希望大家可以根据我的描述找找原因，我们着实是没搞明白🤕

**Comment by Wanghui-Huang** [comment]
感谢反馈，问题已更新&贡献已记录。
