### ISSUE TITLE
3.2.3 启动spark集群失败，web-ui界面中缺少worker

### ISSUE THREAD

**Issue by trevery** [Wanghui-Huang/CQU_bigdata#3]
## 环境：
两台阿里服务器：master 和slave01

## 问题描述：
跟着教程走到`启动Spark集群`的时候。运行如下命令
> sbin/start-slaves.sh

并没有在web ui界面中看到worker，说明slave启动失败。
启动成功应该如下图所示，注意worker：

![image](https://user-images.githubusercontent.com/11856849/93452211-bcc15f00-f90a-11ea-9b6d-6ceeb82b12e9.png)

而运行该命令后并没有启动成功slave。如下图所示：

![image](https://user-images.githubusercontent.com/11856849/93452490-0dd15300-f90b-11ea-8a08-899f1013d186.png)

## 解决方案：

运行如下start-slave命令并输入相关参数，而不是运行start-slaves.sh命令。

> sbin/start-slave.sh spark://localhost:7077  
或者将localhost换成内网ip（我第一次使用上面的可以，第二次上面不可以，需要使用内网ip）
> sbin/start-slave.sh spark://master内网ip:7077 

原因应该是这个命令应该是缺少了主机信息的配置，可以使用start-slave命令指定主机的地址和端口。

**Comment by Wanghui-Huang** [comment]
已更新到最新文档，但是这个issue持续关注下~

**Comment by lympassion** [comment]
`sbin/start-slave.sh spark://master内网ip:7077` 这条命令中开始一直不行，就把`master内网ip`替换成`master外网ip`他就成功了

**Comment by hehaorui** [comment]
也可以在spark的配置文件spark-env.sh最后加一个 export MASTER_PORT=7077 来手动指定MASTER的端口

**Comment by NissonCX** [comment]
2025.11.5，此次实验要求使用华为云，可是华为云Linux没有配备图形化界面，浏览器页面无法直接在命令行清晰展示信息。从自己的Mac端访问又会因为端口权限相关设置难以解决（个人能力不足），是否可以直接将每个人配置成功的截图给老师就完了。（通过在华为云修改相关安全设置已解决）
