### ISSUE TITLE
实验一至实验四遇到的问题及解决措施

### ISSUE THREAD

**Issue by HappyZtao** [Wanghui-Huang/CQU_bigdata#30]
### 前言：

讲讲Lab1到Lab4的报错信息，以及和服务器有关的问题。说来惭愧，已经重装3次系统，就简单讲述一下那些意料之外的报错，希望能帮大家排排雷，如有不当之处，还请大家多多指正。

### 实验一：
**1、问题描述:SSH连接不上的问题**

在一个倒霉的晚上，使用ssh软件多次建立seesion之后，突然报错，无论是MobaXterm，XShell 7，还是putty都无法进入服务器，差点破防了。

显示错误信息：

```
XShell：
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

Connection closed by foreign host.

putty：
Remote side unexpectedly closed network connection

MobaXterm：
Network error： Software caused connection abort.
```

简单来说就是：

远程主机的sshd配置禁止了远程登录/当前用户名登录、当前认证方法。SSH 服务会对相关密钥文件的权限进行检查。比如，私钥文件默认权限是 600，如果配置成 777 等其它权限，导致其它用户也有读取或修改权限。则 SSH 服务会认为该配置存在安全风险，进而导致客户端连接失败。

**解决措施:**

在putty上的解决办法：

![QQ图片20211128175837](https://user-images.githubusercontent.com/88970468/143765040-93976c6e-c174-4021-890e-0c9010be3ea6.jpg)

转载自：https://www.cnblogs.com/elsons/p/15323867.html

在MobaXterm和Xshell上：

首先必须能登录服务器，既然ssh软件都无法进入，那么只能使用最原始的浏览器vnc登录，找到自己的服务器，选择vnc登录。如果无法登陆，那么极有可能是服务器商家把你的ip禁了，及时去解封就可以。登录之后，输入以下命令，更改私钥的权限，重启即可恢复正常。

```
cd /etc/ssh
sudo chmod 644 ./*
sudo chmod 600 ssh_host_dsa_key
sudo chmod 600 ssh_host_rsa_key
sudo chmod 755 .
/etc/init.d/sshd restart
```

**2、问题描述:**

重新配置环境的时候，我们由hadoop2.+版本改换hadoop3.+版本，spark也选择了3.+版本，本来想着升级了版本操作总会少一点问题，结果冒出了新问题。

**解决措施:**

hadoop3和spark3存在着新特性：

master节点配置：
![QQ图片20211128175852](https://user-images.githubusercontent.com/88970468/143765091-708a0f65-cec3-4e8d-825b-63ac53f7f6ef.png)

在配置slaves时，这个文件在新版本里已经不叫slaves，而是叫worker，里面内容和原先的slaves一样，查阅资料显示，这个新文件代替了slaves文件作了优化。

Spark配置：
![QQ图片20211128175858](https://user-images.githubusercontent.com/88970468/143765101-2abb68ac-8ba6-41b1-9c4b-6b7ac53d4bfd.png)

![QQ图片20211128175904](https://user-images.githubusercontent.com/88970468/143765061-57df2fa6-f820-4130-840d-674166500bb1.png)

rk-env.sh本身就存在，无需再次复制。

其中的vim slaves，和上面同理这个slaves这个文件已经消失了，取而代之的是workers。

如果上述两步不进行修改仍然按照原先2.+版本的操作，最后集群测试的时候slave节点上只会出现一个节点，而master拥有所有节点，等效于master本地执行。

**3、问题描述:**

**使用hadoop3.0版本按照实验指导书配置环境后，使用sbin/start-all.sh启动集群，发现两个子节点无法启动，**

**子节点没有DataNode和NodeManager**

**解决措施:**

hadoop3.0与hadoop2.0的环境配置有略微差别,需要在/usr/local/hadoop/etc/hadoop/路径下的

worker文件中把localhost删了添加slave01和slave02

### 实验二：

**4、问题描述:按照实验指导书下载的chromedriver和google-chrome版本不匹配**

**解决措施:**
执行如下命令安装google-chrome:

```text
wget -O /etc/yum.repos.d/CentOS-Base.repo   http://mirrors.aliyun.com/repo/Centos-7.repo

curl https://intoli.com/install-google-chrome.sh | bash
ldd /opt/google/chrome/chrome | grep "not found"

google-chrome --no-sandbox --headless --disable-gpu --screenshot https://www.baidu.com/
```

通过   google-chrome-stable --version   查看google-chrome版本号

然后安装chromedrive:

去https://npm.taobao.org/mirrors/chromedriver/      下载对应版本的chromedrive

上传到服务器后，unzip解压后mv chromedriver /usr/bin/ 移至/usr/bin/路径

**5、问题描述:单元测试输出的结果中文乱码**

**解决措施:**
将#coding: utf8改成 #coding: UTF-8  或者  # -* - coding: UTF-8  -* -

### 实验三：

hadoop3的新特性，由于hdfs的端口变了。需要放通一下9866端口。

**6、问题描述:**
启动集群运行任务后报如下错误:No module name 'numpy', 这可能是其中的一个节点并未安装这个库

![1](https://user-images.githubusercontent.com/88970468/143765004-0b00e065-fa7e-433d-8546-744b85899435.png)

**解决措施:**
需要所有的机器都安装numpy库

集群下的每台机器都需要安装所有项目依赖的相应python库，例如在实验三你需要提前在每台机器上安装matplotlib, pyspark和numpy.

安装numpy库，执行sudo pip3 install numpy 命令后重新启动集群运行运行即可, 

注意前面需要加上sudo，否则安装库时会发生错误(如下所示)

![2](https://user-images.githubusercontent.com/88970468/143764999-ecf737c7-c035-45d3-998c-f1ddd55c3e2c.png)

**7、问题描述：**
执行安装库命令后，下载成功但是安装时出现如下报错: The headers or library files could not be found for jpeg.

![3](https://user-images.githubusercontent.com/88970468/143764989-1b6208cd-d6ed-4206-93e4-5ac519bc356c.png)

**解决措施:** 

这是因为pip版本过旧的原因，通过sudo pip3 install --upgrade pip更新pip后，重新安装相应库即可。

### 实验四：

**8、问题描述: 数据预处理时执行.sh脚本提醒权限不够:**
![4](https://user-images.githubusercontent.com/88970468/143764982-46fc4660-562d-40d5-9130-a5115ea58ed6.png)

**解决措施:**

使用sudo chmod -R 777 Ex4_CustomerForecast/ 递归地赋予文件夹权限即可

**Comment by Wanghui-Huang** [comment]
感谢反馈，已记录贡献&bug修复。
