### ISSUE TITLE
【⚠️  重要】2021年秋·大数据课程开源统计

### ISSUE THREAD

**Issue by Wanghui-Huang** [Wanghui-Huang/CQU_bigdata#32]
各位同学们好：
我们今年大数据课程已经接近尾声，这门课已经开设了三年，每年都会邀请同学们来共同建设。每年我们也都会根据同学们的反馈进行完善，今年我们预计会进行一次更大的系统性更新。
按照当初承诺，现在我们统计下大家开源贡献，请按照示例，在进行下方评论完成填写。

- [注1] ：为保证大家隐私情况，该Issue**会在三天内统计完毕后关闭**，请及时填写~

| 组号 | 贡献类型（文档建设、Issue、PR等） | 链接（或其它证明截图） |               贡献人               | 备注 |
| :--: | :-------------------------------: | :--------------------: | :--------------------------------: | :--: |
| 01组 |               issue               |     [test-issue]()     | 张三（20196666）、李四（20197777） |      |

感谢大家的积极参与！

**Comment by KOBEliever** [comment]
<html>
<body>
<!DOCTYPE html><br class="Apple-interchange-newline">

组号 | 贡献类型（文档建设、Issue、PR等） | 链接（或其他证明截图） | 贡献人 | 备注
-- | -- | -- | -- | --
16组 | Issue | https://github.com/Wanghui-Huang/CQU_bigdata/issues/28 | 丁一（20194265）、陈昭睿（20194238）、王健（20194239） |  


</body>
</html>

**Comment by a-fly-fly-bird** [comment]
| 组号 | 贡献类型（文档建设、Issue、PR 等） | 链接（或其它证明截图）                                       | 贡献人                                                   | 备注 |
| ---- | ---------------------------------- | ------------------------------------------------------------ | -------------------------------------------------------- | ---- |
| 19组 | issue，文档建设                    | 1. [Hadoop 3.0 集群启动测试slave节点只有jps一项的问题 · Issue #19 · Wanghui-Huang/CQU_bigdata (github.com)](https://github.com/Wanghui-Huang/CQU_bigdata/issues/19)<br />2.[实验二执行 bin/spark-submit /home/hadoop/Experiment/Ex2_WordCount/WordCount.py可能遇到的一些问题 · Issue #21 · Wanghui-Huang/CQU_bigdata (github.com)](https://github.com/Wanghui-Huang/CQU_bigdata/issues/21)<br />3. [实验三hadoop 环境报 failed on connection exception · Issue #26 · Wanghui-Huang/CQU_bigdata (github.com)](https://github.com/Wanghui-Huang/CQU_bigdata/issues/26)<br />4.[关于在华为云上搭建 Hadoop3 + Spark3 分布式环境的一些尝试 · Issue #27 · Wanghui-Huang/CQU_bigdata (github.com)](https://github.com/Wanghui-Huang/CQU_bigdata/issues/27) |  谭勇@a-fly-fly-bird（20194278），赵苏博（20194274），蔡为凯（20194264） |    4是文档建设  |

**Comment by Wangzt670** [comment]
[贡献统计.md](https://github.com/Wanghui-Huang/CQU_bigdata/files/7616899/default.md)

**Comment by Wangzt670** [comment]
[贡献统计.md](https://github.com/Wanghui-Huang/CQU_bigdata/files/7616904/default.md)

**Comment by Wangzt670** [comment]
[贡献统计.md](https://github.com/Wanghui-Huang/CQU_bigdata/files/7616923/default.md)

**Comment by Wangzt670** [comment]
| 组号 | 贡献类型（文档建设、Issue、PR等）                            | 链接（或其它证明截图）                                       | 备注 | 贡献人                                                 |
| :--- | ------------------------------------------------------------ | ------------------------------------------------------------ | ---- | ------------------------------------------------------ |
| 02组 | **Issue**：实验二：指导书外报错汇总、实验三：指导书外报错汇总，**文档建设**：实验4的src目录和下面的数据集 | https://github.com/Wanghui-Huang/CQU_bigdata/issues/23、https://github.com/Wanghui-Huang/CQU_bigdata/issues/24、![image-20211129165008565](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211129165008565.png)、![image-20211129165656841](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211129165656841.png) |      | 王正霆（20194249）、王开发（20194235）、崔晋（20191682 |

**Comment by leexinhao** [comment]
| 组号 | 贡献类型（文档建设、Issue、PR 等） | 链接（或其它证明截图） | 贡献人                         | 备注 |
| ---- | ---------------------------------- | ---------------------- | ------------------------------ | ---- |
| 9    | issue，文档建设                    | 1. issue：https://github.com/Wanghui-Huang/CQU_bigdata/issues/22 <br> 2. 文档建设：https://github.com/Wanghui-Huang/CQU_bigdata/pull/33  | 李新浩（20185525）<br> 杨旭峰（20192680）<br> 孟川洋（20193575）|      |

**Comment by Wangzt670** [comment]
| 组号 | 贡献类型（文档建设、Issue、PR等）                            | 链接（或其它证明截图）                                       | 备注 | 贡献人                                                  |
| :--- | ------------------------------------------------------------ | ------------------------------------------------------------ | ---- | ------------------------------------------------------- |
| 02组 | **Issue**：实验二：指导书外报错汇总、实验三：指导书外报错汇总，**文档建设**：实验4的src目录和下面的数据集 | 1.https://github.com/Wanghui-Huang/CQU_bigdata/issues/23    2.https://github.com/Wanghui-Huang/CQU_bigdata/issues/24  3.![image-20211129165008565](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211129165008565.png)4.![image-20211129165656841](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211129165656841.png) |      | 王正霆（20194249）、王开发（20194235）、崔晋（20191682) |

**Comment by Wangzt670** [comment]
| 组号 | 贡献类型（文档建设、Issue、PR等）                            | 链接（或其它证明截图）                                       | 贡献人                                                  | 备注 |
| :--- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------- | ---- |
| 02组 | **Issue**：实验二：指导书外报错汇总、实验三：指导书外报错汇总，**文档建设**：实验4的src目录和下面的数据集 | 1.https://github.com/Wanghui-Huang/CQU_bigdata/issues/23    2.https://github.com/Wanghui-Huang/CQU_bigdata/issues/24  3.![image-20211129165008565](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211129165008565.png)4.![image-20211129165656841](https://wangzt670-img.oss-cn-beijing.aliyuncs.com/img/image-20211129165656841.png) | 王正霆（20194249）、王开发（20194235）、崔晋（20191682) |      |

**Comment by Yizhang-Zhu** [comment]
| 组号 | 贡献类型        | 链接                                                         | 贡献人                                                     | 备注 |
| ---- | --------------- | ------------------------------------------------------------ | ---------------------------------------------------------- | ---- |
| 01    | issue | https://github.com/Wanghui-Huang/CQU_bigdata/issues/25#issue-1059299464 | 朱绎彰（20194113）、何钰煌（20194114）、张一帆（20194109） |      |

**Comment by ghc2000** [comment]
<html>
<body>
<!DOCTYPE html>

组号 | 贡献类型（文档建设、Issue、PR等） | 链接（或其他证明截图） | 贡献人 | 备注
-- | -- | -- | -- | --
13组 | 文档建设《远程连接教程》 |  
![_2~BD(`Z}D1A}6ZP0NXHXVP](https://user-images.githubusercontent.com/69564563/143843795-80e2d918-56af-4675-a91b-07924deefcb3.jpg)
![image](https://user-images.githubusercontent.com/69564563/143843843-b0b66941-c7e8-4a7a-bff7-1499c96bd963.png)
 | 高鸿成（20183350） |  


</body>
</html>

**Comment by ghc2000** [comment]
<html>
<body>
<!DOCTYPE html>

组号 | 贡献类型（文档建设、Issue、PR等） | 链接（或其他证明截图） | 贡献人 | 备注
-- | -- | -- | -- | --
13组 | 文档建设《远程连接教程》 | 
![image](https://user-images.githubusercontent.com/69564563/143844044-1e3ea1b2-ce13-4725-9320-db174a5978f3.png)
![_2~BD(`Z}D1A}6ZP0NXHXVP](https://user-images.githubusercontent.com/69564563/143844099-1d48d28b-aba8-41f8-9411-a1690e8091b6.jpg)
  | 高鸿成（20183350） |  


</body>
</html>

**Comment by HappyZtao** [comment]
| 组号 | 贡献类型 |                          链接                          |                    贡献人                     | 备注 |
| :--: | :------: | :----------------------------------------------------: | :-------------------------------------------: | ---- |
| 03组 |  issue   | https://github.com/Wanghui-Huang/CQU_bigdata/issues/30 | 20194142 夏闻远 20194119 张涛 20194167 任君彬 |      |

**Comment by ghc2000** [comment]
| 组号 | 贡献类型（文档建设、Issue、PR等） | 链接（或其它证明截图）                                       | 贡献人             | 备注 |
| ---- | --------------------------------- | ------------------------------------------------------------ | ------------------ | ---- |
| 13组 | 文档建设                          | Vscode/pycharm远程开发教程 #34[[add IDE tutorial by Info4Rec · Pull Request #34 · Wanghui-Huang/CQU_bigdata · GitHub](https://github.com/Wanghui-Huang/CQU_bigdata/pull/34)] | 高鸿成（20183350） |      |

**Comment by sunshine1502** [comment]
<html>
<body>





13组 | issue | #35 | 张倩（20191696），黄梓莹（20194257），胡嘉煜（20194258）

<br class="Apple-interchange-newline">
</body>
</html>
