### ISSUE TITLE
实验1-实验3问题汇总

### ISSUE THREAD

**Issue by sunshine1502** [Wanghui-Huang/CQU_bigdata#35]
提交小组：
20191696 张倩   
20194257 黄梓莹
20194258 胡嘉煜

实验一问题
① 问题描述：安装python3时，yum仓库没有python3的安装包，如图1；因此在执行‘sudo yum install python3.x86_64’语句时报错，如图2所示。
![图片1](https://user-images.githubusercontent.com/75115843/144881661-eec1a239-945b-4797-9d0c-d02c923ea836.png)

                                                             图1
![图片2](https://user-images.githubusercontent.com/75115843/144881679-39a5b38b-2a37-4e1a-9af4-938244ebda74.png)

图2
问题解决：
安装epel使用阿里云镜像：yum install -y epel-release；再输入sudo yum install python3 安装python3，然后进入python环境测试。
![图片3](https://user-images.githubusercontent.com/75115843/144881705-844d0457-edce-4796-8c61-edf594e98311.png)

② 问题描述：master启动集群之后master上运行jps命令，没有进程ResourceManager，而两个slaves只有jps一个进程

![图片4](https://user-images.githubusercontent.com/75115843/144881733-8b6059d4-2aa6-4828-ad21-4ef4755dca86.png)

问题解决：
由于所安装的hadoop版本为3.3.0，该版本不再使用slaves文件进行从机配置，而是使用workers文件，故修改workers文件进行配置。
但在配置过程中，由于打开了其他目录下的workers文件进行配置，导致只有一个从机添加进去，而另一个从机并未添加，如下图所示
![图片5](https://user-images.githubusercontent.com/75115843/144881757-f7120c21-0bfc-4391-bab3-25109b600b18.png)

在查看workers的真实目录后，修改真实workers文件才得以解决。

③问题描述：启动spark集群后，主从机jps均正确，但浏览器中master:8080界面无workers，创建安全组后仍然无法显示。
问题解决：
检查hosts文件，发现master的hosts文件在上一次尝试修改后并未改正回来，slave01的master文件并未修改，在修改这两个文件过后便可正确运行。 

实验二问题
①下载WordCount库时出现报错
![图片6](https://user-images.githubusercontent.com/75115843/144881934-6d47260e-49ed-43b1-8a82-c49477809925.png)

解决方案：
先更新pip，之后再下载即可

![图片7](https://user-images.githubusercontent.com/75115843/144881976-b2d485c8-62be-4cd0-bc69-7ace07212169.png)
![图片8](https://user-images.githubusercontent.com/75115843/144882009-9667fe6b-cfde-4909-a499-b132bc840ead.png)

②在检验WordCount.py文件的正确性时报错 zip（）的第二个参数不可迭代。
![图片9](https://user-images.githubusercontent.com/75115843/144882039-d6a5f760-04d3-4bbe-8155-28cb82b4b46c.png)

解决方案：
根据报错信息，第二个zip元素中的元素是不可迭代的，我们的第二个元素是1是一个整型变量并不是列表等可迭代的元素，因此不能使用zip(), 在查询资料后，发现只需要变为.map(lambda word: (word,1))即可。
③转发请求问题
![图片10](https://user-images.githubusercontent.com/75115843/144882109-dd689773-4bf5-4f71-8455-b512477e0944.png)

解决方案：下载Xmanager
④下载Xmanager后仍显示找不到Xmananger   
![图片11](https://user-images.githubusercontent.com/75115843/144882143-866c9db9-6116-423d-be0f-9bb7a3929379.png)

解决方法：
Xshell与Xmanager版本不匹配 升级Xshell6到Xshell7。

⑤运行代码提示echarts is not defined
![图片12](https://user-images.githubusercontent.com/75115843/144882183-2abb42f2-a27e-4f02-a87b-5a8ffa35b2d0.png)

解决方案：卸载重装snapshot_selenium，问题解决。
⑥在测试python文件时报错ChromeDriver与Chrome版本不匹配，检查过后发现ChromeDriver版本为90，Chrome的版本为95。
![图片13](https://user-images.githubusercontent.com/75115843/144882218-a7762a1d-a605-46a3-95bc-38c646169eb4.png)

![图片14](https://user-images.githubusercontent.com/75115843/144882246-edc50506-ee54-4e56-9aef-a2f6667683e2.png)

解决方案：
用wget 命令下载ChromeDriver 95的安装包，并解压到usr/bin文件夹下即可。
![图片15](https://user-images.githubusercontent.com/75115843/144882275-6c0e0526-5953-42eb-ab5a-b9e39080f170.png)

⑦报错results文件夹不存在。
![图片16](https://user-images.githubusercontent.com/75115843/144882310-c2a71c99-947d-4059-b8c1-5d49e0fde8b7.png)

解决方法：
查看上级文件夹，发现没有results文件夹，然后新建同名文件夹。
![图片17](https://user-images.githubusercontent.com/75115843/144882354-7f336964-5a29-4ff9-b3bc-b3a9b1d8f210.png)

新建后：
![图片18](https://user-images.githubusercontent.com/75115843/144882383-2f460b5c-7e80-44f5-a125-be44bb725db8.png)

实验三问题：
①显示拒绝连接
![图片19](https://user-images.githubusercontent.com/75115843/144882414-c13803a8-5a01-4d96-92ba-075d93e9c687.png)

问题解决：
打开hadoop集群和spark集群，且安全组添加9000端口，并放通

②9866端口未添加
![图片20](https://user-images.githubusercontent.com/75115843/144882457-799d474b-ec22-4c96-9273-e29fc724badb.png)

解决方案:
将主机和从机均添加9866端口，并放通

③提交到分布式集群中会出现内存不足的警告，且一个多小时没有运行出来。
![图片21](https://user-images.githubusercontent.com/75115843/144882585-b42cd1e4-4f49-43c3-aa2b-cdfedb904f55.png)

下图为kill掉的进程
![图片22](https://user-images.githubusercontent.com/75115843/144882627-d1075e5d-ec86-447c-a07b-340ff9284892.png)

查看从机空闲内存，均大于1G
![图片23](https://user-images.githubusercontent.com/75115843/144882669-524930cf-b7c7-4805-824e-0834e390223e.png)
![图片24](https://user-images.githubusercontent.com/75115843/144882697-0e472955-e88f-4302-8d99-970e58a6a437.png)
![图片25](https://user-images.githubusercontent.com/75115843/144882735-89b583a3-c83a-4b2d-8063-dffbde13eb98.png)

解决方案：
在询问助教后，采用单机版运行

④PiplinedRDD没有toDF()这一方法
![图片26](https://user-images.githubusercontent.com/75115843/144882776-4018f2aa-52d7-41b1-9df4-7ab135ccb26a.png)

解决方案：
在iris.py代码中加入from pyspark.sql import SQLContext sqlContext = SQLContext(sc)
![图片27](https://user-images.githubusercontent.com/75115843/144882806-ba566f0a-19cc-4d79-9fa3-eb2a1e51f348.png)

⑤路径错误 
![图片28](https://user-images.githubusercontent.com/75115843/144882833-a181ebd6-1165-48db-8b0f-83641ef05e02.png)

解决方案：
在路径前加file:/// (是三个斜杠，两个斜杠会报错)
![图片29](https://user-images.githubusercontent.com/75115843/144882865-c4f94a9f-3950-45ee-9700-e3a7e7154fe1.png)

⑥kmeansModel没有computCost（）方法
![图片30](https://user-images.githubusercontent.com/75115843/144882902-c0d46c22-58d3-466e-bfe2-30ee12a88e8a.png)

解决方案：
由于我们安装的是spark 3.2.0版本，故需要使用ClusterEvaluator代替computeCost方法来进行模型评价，修改代码如下
![图片31](https://user-images.githubusercontent.com/75115843/144882970-e7b2ed7f-a370-42d4-aaff-910f3b302597.png)

**Comment by Wanghui-Huang** [comment]
感谢反馈，已记录贡献 & 问题已修复。
