### ISSUE TITLE
词频统计正确，可视化提示出错

### ISSUE THREAD

**Issue by lympassion** [Wanghui-Huang/CQU_bigdata#5]
**词频统计正确**
 
![Picture1](https://user-images.githubusercontent.com/48206934/93971411-b582d100-fda2-11ea-8003-6343fbb14737.png)

   但当要生成可视化图表时提示

**selenium. common. exception. webdriver exception: message: chrome not reachable**
（这个当时没有截屏）
网上搜说出现这个的可能原因是chromedriver程序占用了端口。
**解决方法：**
控制台登录服务器之后重启(重启时间可能在5-10分钟)再重新运行命令即可。

**Comment by Wanghui-Huang** [comment]
感谢反馈，上次看到但是你已经解决了就忘记回复了~
下次更新到最新文档，会关闭issue~ 🥰

**Comment by Wanghui-Huang** [comment]
已更新到最新文档，所以该issue被关闭。

**Comment by pengyuyan255** [comment]
解决了个锤子

> **词频统计正确**
> 
> ![Picture1](https://user-images.githubusercontent.com/48206934/93971411-b582d100-fda2-11ea-8003-6343fbb14737.png)
> 
> 但当要生成可视化图表时提示
> 
> **selenium. common. exception. webdriver exception: message: chrome not reachable** （这个当时没有截屏） 网上搜说出现这个的可能原因是chromedriver程序占用了端口。 **解决方法：** 控制台登录服务器之后重启(重启时间可能在5-10分钟)再重新运行命令即可。

解决了个锤子

**Comment by pengyuyan255** [comment]
> **词频统计正确**
> 
> ![Picture1](https://user-images.githubusercontent.com/48206934/93971411-b582d100-fda2-11ea-8003-6343fbb14737.png)
> 
> 但当要生成可视化图表时提示
> 
> **selenium. common. exception. webdriver exception: message: chrome not reachable** （这个当时没有截屏） 网上搜说出现这个的可能原因是chromedriver程序占用了端口。 **解决方法：** 控制台登录服务器之后重启(重启时间可能在5-10分钟)再重新运行命令即可。

解决了个锤子
