### ISSUE TITLE
清华镜像站的Spark已经没有2.4.4版本了

### ISSUE THREAD

**Issue by vanues** [Wanghui-Huang/CQU_bigdata#6]
现在最近的版本是2.4.7
https://mirrors.tuna.tsinghua.edu.cn/apache/spark/spark-2.4.7/spark-2.4.7-bin-without-hadoop.tgz

**Comment by Wanghui-Huang** [comment]
感谢反馈，这个问题已经在github最新文档进行更新了。
- 可转入最新文档查看[ex2.md](https://github.com/Wanghui-Huang/CQU_bigdata/blob/master/Experiment/Ex1_SettingUpEnvironment/ex1.md)

- 也可查看下面截图![image](https://user-images.githubusercontent.com/23701880/94567217-ca2d0080-029d-11eb-92f5-9a4cdfb5d510.png)

**Comment by Wanghui-Huang** [comment]
因为问题已经解决，所以该issue被关闭~
欢迎下次继续更新反馈，我们期末考核都会记录并给予一定鼓励措施 😅
