### ISSUE TITLE
实验三：KMeans&Spark分布式实践 云服务器分布式文件系统 上传数据集出错

### ISSUE THREAD

**Issue by KarlThelor** [Wanghui-Huang/CQU_bigdata#7]
![大数据](https://user-images.githubusercontent.com/60059677/95587117-395fdd00-0a74-11eb-8c39-d67b03110337.jpg)

通过云服务器将本地文件 iris.data 上传到 hdfs://master:9000/ex/ex3dataset/iris.datat 时，系统提示连接超时。

`org.apache.hadoop.net.ConnectTimeoutException: 60000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=/47.99.124.142:50010] `

将服务器的防火墙关闭也不能解决问题。

**Comment by yacaikk** [comment]
以阿里云为例，去控制台选择网络与安全下的安全组，配置规则。将连接超时的50010端口开放即可。配置规则如图
![QQ图片20201009215521](https://user-images.githubusercontent.com/36555405/95591743-4bdd1500-0a7a-11eb-8370-8d2e9cda04c3.png)

**Comment by Wanghui-Huang** [comment]
给师弟手动点赞，一般云服务器网络问题通常都是安全组端口配置问题。为了方便，大家可以设置安全组手动将服务器释放所有端口（存在些安全隐患）：
- [腾讯云文档：安全组端口配置](https://cloud.tencent.com/document/product/213/2502)

**Comment by Wanghui-Huang** [comment]
已更新到最新文档，所以该issue被关闭。
