### ISSUE TITLE
ex1-3.2.3 Sprak启动后webui中没有worker

### ISSUE THREAD

**Issue by iDream-G** [Wanghui-Huang/CQU_bigdata#8]
![image](https://user-images.githubusercontent.com/47743977/95651858-a11f3200-0b1f-11eb-8674-d74ebffe1689.png)
在这一步，最开始使用的内网IP，启动Spark后webui上无法看到worker。
将上述内网IP替换为公网IP后，重新启动正常。

**Comment by Wanghui-Huang** [comment]
已更新到最新文档。
